spring.application.name=example-console

## TalkativeBot configuration
## 1. PendingInteraction store: memory (Conversation facts are stored in memory)
## 3. Declare the package that contains definitions for scanning **VERY IMPORTANT**
## 4. Detect and start all auto-startable channels (e.g., console), whether provided by TalkativeBot or your own custom channels
## 5. To start the console channel, you must explicitly enable it
atchurey.tools.talkativebot.pending-interaction.store=memory
atchurey.tools.talkativebot.topic-base-package=com.example.console.topics
atchurey.tools.talkativebot.channels.enabled=true
atchurey.tools.talkativebot.channels.console-enabled=true
